### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by Psydwinder** [fac26/week-4-serverside-lid#52]
When trying to sign up we get the following error in the terminal

Error from hashing the password, something went wrong with bcrypt.hash ReferenceError: sanitize is not defined
    at C:\Users\maste\Desktop\Code-review\week-4-serverside-lid\src\routes\sign-up.js:32:9

The person is also not added to the database

![image](https://user-images.githubusercontent.com/101563800/217608102-ef3dbf59-876e-4bd2-9cbb-27b9db9078a2.png)

**Comment by LauraK0** [comment]
Thanks, this issue was resolved. An error was thrown due to this line being commented out.

![Screenshot 2023-02-09 at 11 46 05](https://user-images.githubusercontent.com/108976875/217804280-dcc5fbf4-2ef9-4b05-aa5c-69c542945a3e.png)

**Comment by DominicSimpson** [comment]
Thanks, Laura.
